defaults:
  - _self_
  - augmentations: multicrop.yaml
  - wandb: private.yaml
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

# disable hydra outputs
hydra:
  output_subdir: null
  run:
    dir: .

name: "frossl-mit67" # change here for cifar100
method: "frossl"
backbone:
  name: "resnet50"
method_kwargs:
  proj_hidden_dim: 2048
  proj_output_dim: 1024
  alpha: 2
  kernel_type: "linear"
  invariance_weight: 1.4

data:
  dataset: mit67 # change here for cifar100
  train_path: "./datasets/mit67/train_images"
  val_path: "./datasets/mit67/test_images"
  format: "image_folder"
  num_workers: 8
optimizer:
  name: "lars"
  batch_size: 64
  lr: 0.3
  classifier_lr: 0.1
  weight_decay: 1e-4
  kwargs:
    clip_lr: True
    eta: 0.02
    exclude_bias_n_norm: True
scheduler:
  name: "warmup_cosine"
checkpoint:
  enabled: True
  dir: "trained_models"
  frequency: 1
auto_resume:
  enabled: False

# overwrite PL stuff
max_epochs: 1
devices: [0]
sync_batchnorm: True
accelerator: "gpu" 
strategy: "ddp"
precision: 32