defaults:
  - _self_
  - augmentations: asymmetric.yaml
  - wandb: private.yaml
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

# disable hydra outputs
hydra:
  output_subdir: null
  run:
    dir: .

name: "frossl-cifar10" # change here for cifar100
method: "frossl"
backbone:
  name: "resnet18"
method_kwargs:
  proj_hidden_dim: 512
  proj_output_dim: 512
  alpha: 2
  kernel_type: "linear"
  invariance_weight: 1.0

data:
  dataset: office_home # change here for cifar100
  train_path: "./datasets"
  val_path: "./datasets"
  format: "image_folder"
  num_workers: 2 #original was 8
optimizer:
  name: "lars"
  batch_size: 128
  lr: 0.08
  classifier_lr: 0.1
  weight_decay: 1e-4
  kwargs:
    clip_lr: True
    eta: 0.02
    exclude_bias_n_norm: True
scheduler:
  name: "warmup_cosine"
checkpoint:
  enabled: True
  dir: "trained_models"
  frequency: 2
auto_resume:
  enabled: False

# overwrite PL stuff
max_epochs: 50
devices: [0]
sync_batchnorm: True
accelerator: "gpu"
strategy: "ddp"
precision: 32
